package org.jahia.support.modulemanagement.rest;

import org.apache.commons.fileupload.FileItemIterator;
import org.apache.commons.fileupload.FileItemStream;
import org.apache.commons.fileupload.FileUploadException;
import org.apache.commons.fileupload.servlet.ServletFileUpload;
import org.jahia.services.content.JCRSessionFactory;
import org.jahia.services.usermanager.JahiaUser;
import org.jahia.services.usermanager.JahiaUserManagerService;
import org.jahia.support.modulemanagement.ModuleManagementCommunityService;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.servlet.Servlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;

/**
 * HTTP POST servlet that accepts a module snapshot ZIP archive and imports it.
 *
 * <p>Registered at {@code /module-management-community/import}.
 *
 * <p>Expects a multipart/form-data body with a field named {@code archive} (or {@code file})
 * containing a {@code .zip} file previously generated by the export endpoint.
 */
@Component(
        service = Servlet.class,
        property = {"alias=/module-management-community/import"},
        immediate = true
)
public class ModuleArchiveImportServlet extends HttpServlet {

    private static final Logger logger = LoggerFactory.getLogger(ModuleArchiveImportServlet.class);
    private static final long MAX_ARCHIVE_SIZE = 500L * 1024 * 1024; // 500 MB

    @Reference
    private ModuleManagementCommunityService moduleManagementCommunityService;

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
        response.setContentType("application/json;charset=UTF-8");
        response.setCharacterEncoding("UTF-8");

        String origin = request.getHeader("Origin");
        if (origin != null) {
            response.setHeader("Access-Control-Allow-Origin", origin);
            response.setHeader("Vary", "Origin");
        }

        PrintWriter writer = response.getWriter();

        // --- Authentication check ---
        JahiaUser currentUser = JCRSessionFactory.getInstance().getCurrentUser();
        if (currentUser == null || JahiaUserManagerService.isGuest(currentUser)) {
            response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
            writer.write("{\"error\":\"Authentication required\"}");
            return;
        }

        // --- Multipart check ---
        if (!ServletFileUpload.isMultipartContent(request)) {
            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
            writer.write("{\"error\":\"Multipart request required\"}");
            return;
        }

        try {
            ServletFileUpload upload = new ServletFileUpload();
            upload.setFileSizeMax(MAX_ARCHIVE_SIZE);

            FileItemIterator iterator = upload.getItemIterator(request);
            while (iterator.hasNext()) {
                FileItemStream item = iterator.next();
                String fieldName = item.getFieldName();
                if (!item.isFormField() && ("archive".equals(fieldName) || "file".equals(fieldName))) {
                    String fileName = sanitizeFileName(item.getName());
                    if (!fileName.toLowerCase().endsWith(".zip")) {
                        response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
                        writer.write("{\"error\":\"Only .zip archive files are accepted\"}");
                        return;
                    }

                    logger.info("Received archive import request for file: '{}' by user: '{}'",
                            fileName, currentUser.getName());

                    try (InputStream stream = item.openStream()) {
                        String result = moduleManagementCommunityService.importModuleArchive(stream, fileName);
                        writer.write("{\"message\":" + toJsonString(result) + "}");
                    }
                    return;
                }
            }

            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
            writer.write("{\"error\":\"No 'archive' or 'file' field found in the multipart request\"}");

        } catch (FileUploadException e) {
            logger.error("Error parsing multipart archive upload", e);
            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
            writer.write("{\"error\":" + toJsonString(e.getMessage()) + "}");
        } catch (IOException e) {
            logger.error("Error importing module archive", e);
            response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
            writer.write("{\"error\":" + toJsonString(e.getMessage()) + "}");
        }
    }

    @Override
    protected void doOptions(HttpServletRequest request, HttpServletResponse response) {
        String origin = request.getHeader("Origin");
        if (origin != null) {
            response.setHeader("Access-Control-Allow-Origin", origin);
            response.setHeader("Vary", "Origin");
        }
        response.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
        response.setHeader("Access-Control-Allow-Headers", "Content-Type, X-Requested-With");
        response.setStatus(HttpServletResponse.SC_OK);
    }

    private String sanitizeFileName(String raw) {
        if (raw == null) {
            return "archive.zip";
        }
        int lastSlash = Math.max(raw.lastIndexOf('/'), raw.lastIndexOf('\\'));
        return lastSlash >= 0 ? raw.substring(lastSlash + 1) : raw;
    }

    private String toJsonString(String value) {
        if (value == null) {
            return "null";
        }
        return "\"" + value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t") + "\"";
    }
}

