package org.jahia.support.modulemanagement.rest;

import org.apache.commons.fileupload.FileItemIterator;
import org.apache.commons.fileupload.FileItemStream;
import org.apache.commons.fileupload.FileUploadException;
import org.apache.commons.fileupload.servlet.ServletFileUpload;
import org.jahia.services.securityfilter.PermissionService;
import org.jahia.services.usermanager.JahiaUser;
import org.jahia.support.modulemanagement.ModuleManagementCommunityService;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.servlet.Servlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;

/**
 * HTTP POST servlet that accepts a module snapshot ZIP archive and imports it.
 *
 * <p>Registered at {@code /module-management-community/import}.
 *
 * <p>Expects a multipart/form-data body with a field named {@code archive} (or {@code file})
 * containing a {@code .zip} file previously generated by the export endpoint.
 */
@Component(
        service = Servlet.class,
        property = {"alias=/module-management-community/import"},
        immediate = true
)
public class ModuleArchiveImportServlet extends AbstractModuleManagementServlet {

    private static final Logger logger = LoggerFactory.getLogger(ModuleArchiveImportServlet.class);
    private static final long MAX_ARCHIVE_SIZE = 500L * 1024 * 1024; // 500 MB
    private static final String ERROR_IMPORT_FAILED = "{\"error\":\"Import failed\"}";

    private final transient ModuleManagementCommunityService moduleManagementCommunityService;

    @Activate
    public ModuleArchiveImportServlet(
            @Reference ModuleManagementCommunityService moduleManagementCommunityService,
            @Reference PermissionService permissionService) {
        super(permissionService);
        this.moduleManagementCommunityService = moduleManagementCommunityService;
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) {
        handleMultipartPost(request, response, "module-management-community.import", logger, this::handleImport);
    }

    private void handleImport(HttpServletRequest request, HttpServletResponse response, PrintWriter writer, JahiaUser currentUser) {
        try {
            ServletFileUpload upload = new ServletFileUpload();
            upload.setFileSizeMax(MAX_ARCHIVE_SIZE);

            FileItemIterator iterator = upload.getItemIterator(request);
            while (iterator.hasNext()) {
                FileItemStream item = iterator.next();
                String fieldName = item.getFieldName();
                if (!item.isFormField() && ("archive".equals(fieldName) || "file".equals(fieldName))) {
                    processArchiveItem(item, response, writer, currentUser);
                    return;
                }
            }

            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
            writer.write("{\"error\":\"No 'archive' or 'file' field found in the multipart request\"}");
        } catch (FileUploadException e) {
            logger.error("Error parsing multipart archive upload", e);
            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
            writer.write("{\"error\":\"Invalid multipart upload\"}");
        } catch (IOException e) {
            // Detail is logged server-side only; clients get a generic message (no internal leak).
            logger.error("Error importing module archive", e);
            response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
            writer.write(ERROR_IMPORT_FAILED);
        }
    }

    private void processArchiveItem(FileItemStream item, HttpServletResponse response, PrintWriter writer, JahiaUser currentUser) throws IOException {
        String fileName = ServletSupport.sanitizeFileName(item.getName(), "archive.zip");
        if (!fileName.toLowerCase().endsWith(".zip")) {
            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
            writer.write("{\"error\":\"Only .zip archive files are accepted\"}");
            return;
        }

        if (logger.isInfoEnabled()) {
            logger.info("Received archive import request for file: '{}' by user: '{}'",
                    fileName, ServletSupport.sanitizeForLog(currentUser.getName()));
        }

        try (InputStream stream = item.openStream()) {
            String result = moduleManagementCommunityService.importModuleArchive(stream, fileName);
            writer.write("{\"message\":" + ServletSupport.toJsonString(result) + "}");
        }
    }

    @Override
    protected void doOptions(HttpServletRequest request, HttpServletResponse response) {
        handleOptions(request, response, "POST, OPTIONS");
    }
}
