package org.jahia.support.modulemanagement;

import org.apache.karaf.features.Feature;
import org.jahia.support.modulemanagement.UpdateModulesResult;
import org.osgi.framework.Bundle;

import javax.jcr.RepositoryException;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Set;

public interface ModuleManagementCommunityService {

    /**
     * Deploy an uploaded module JAR to the OSGi framework via the provisioning manager.
     *
     * @param fileStream the input stream of the JAR file
     * @param fileName   the original file name (used for logging and validation)
     * @return a human-readable result message
     * @throws IOException if validation or deployment fails
     */
    String deployUploadedModule(InputStream fileStream, String fileName) throws IOException;

    /**
     * Export deployed Jahia bundles (module / system / templatesSet types only) as a
     * self-contained ZIP archive with an embedded {@code provisioning.yaml}.
     * Maven-resolvable bundles are referenced by their {@code mvn:} URL; bundles only
     * available as local JAR files are embedded under {@code bundles/}.
     *
     * @param options filtering options (types, etc.)
     * @return a temporary ZIP file — the caller MUST delete it after streaming it to the client
     * @throws IOException if bundle resolution or ZIP assembly fails
     */
    File exportModulesArchive(ExportOptions options) throws IOException;

    /**
     * Return the provisioning YAML that would be generated by {@link #exportModulesArchive}
     * without actually building the ZIP.  Useful for a "preview" UI.
     *
     * @param options same filtering options as export
     * @return the YAML content as a string
     * @throws IOException if bundle listing fails
     */
    String previewExportYaml(ExportOptions options) throws IOException;

    /**
     * Import a module snapshot archive previously created by {@link #exportModulesArchive}.
     * Extracts the ZIP to a temp directory, rewrites the embedded {@code ${archiveRoot}}
     * placeholder to the actual extraction path, then executes {@code provisioning.yaml}
     * via the provisioning manager.
     *
     * @param zipStream   stream of the uploaded ZIP file
     * @param archiveName original file name (used for logging)
     * @return a human-readable summary message
     * @throws IOException if extraction or execution fails
     */
    String importModuleArchive(InputStream zipStream, String archiveName) throws IOException;

    UpdateModulesResult updateModules(boolean jahiaOnly, boolean dryRun, List<String> filters, boolean autostart, boolean uninstallPrevious, boolean forceUpdateAll, boolean onStartup) throws IOException;

    Set<String> listAvailableUpdates(boolean jahiaOnly, List<String> filters, boolean forceUpdate) throws IOException;

    List<Feature> getFeatures(boolean jahiaOnly, List<String> filters) throws IOException;

    Set<String> getInstalledModules() throws IOException;

    Instant getLastUpdateTime();

    Bundle getBundleById(long bundleId);

    Map<String, Boolean> getSitesDeployment(Bundle bundle) throws RepositoryException;

    boolean enableModuleOnSites(Bundle bundle, Set<String> sites);
    boolean disableModuleOnSites(Bundle bundle, Set<String> sites);

    boolean importModule(Bundle bundle, boolean force) throws IOException;

    List<Map<String, Object>> getBundleVersionsFromJcr(Bundle bundle) throws RepositoryException;

    String installBundleVersionFromJcr(String jcrPath) throws IOException;

    /**
     * Remove old module versions from the JCR module-management store
     * ({@code /module-management/bundles/…}), retaining for each module:
     * <ol>
     *   <li>all versions currently installed in OSGi (any state), and</li>
     *   <li>at most one additional "previous" version (the most recent one not already in OSGi).</li>
     * </ol>
     * This keeps storage under control while still allowing a quick roll-back.
     *
     * @return a human-readable summary (number of version folders removed, bytes freed)
     * @throws RepositoryException if JCR access fails
     */
    String cleanupJcrVersions() throws RepositoryException;
}
